### ISSUE TITLE
what does trial_file signifies?

### ISSUE THREAD

**Issue by anamika06jain** [zengchang94622/MTGAN#1]
what does trial_file signifies? and in what sequence the files should be in trial_pair.csv?

**Comment by zengchang233** [comment]
> what does trial_file signifies? and in what sequence the files should be in trial_pair.csv?

Thanks for watching this repository. You can find the format of trial file from Voxceleb1 Test by this link: http://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test.txt
